{{- range $key, $item := .Values.external_secrets }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $key }}
spec:
  backendType: secretsManager
  data:
    {{- range $item.values }}
    - key: {{ $.Release.Name }}/{{ $item.key }}
      name: {{ . }}
      {{- if contains "cred" $key }}
      property: {{ . }}
      {{- end }}
    {{- end }}
---
{{- end }}