{{- range $hook_name, $hook_values := .Values.hooks }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $hook_name }}
  annotations:
    "helm.sh/hook": {{ $hook_values.hook }}
    "helm.sh/hook-weight": {{ default -5 $hook_values.weight | quote  }}
spec:
  template:
    spec:
          containers:
            - name: {{ $hook_name }}
              image: {{ template "ecrUrl" $}}/{{ $hook_values.imageName }}:{{ $.Values.deployment.branchName }}.{{ $.Values.deployment.buildNumber }}
              imagePullPolicy: Always
              command:
              {{- range $hook_values.command }}
                - {{ . }}
              {{- end }}
              env:
                {{- range $envVarName, $envVarValue := $.Values.deployment.env }}
                - name: {{ $envVarName }}
                  value: {{ $envVarValue | quote }}
                {{- end }}
                - name: RELEASE_NAME
                  value: {{ $.Release.Name }}
                {{- range $key, $value := $hook_values.env }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
                {{- if eq $.Release.Name "staging"}}
                {{- range $envVarName, $envVarValue := $.Values.deployment.stagingEnvVars }}
                - name: {{ $envVarName }}
                  value: {{ $envVarValue | quote }}
                {{- end }}
                {{- else if and (ne $.Release.Name "prodcution") (ne $.Release.Name "prod") (ne $.Release.Name "stage") (ne $.Release.Name "staging") }}
                {{- range $envVarName, $envVarValue := $.Values.deployment.demoEnvVars }}
                - name: {{ $envVarName }}
                  value: {{ $envVarValue | quote }}
                {{- end }}
                {{- end }}
                {{- range $key, $value := $.Values.secrets }}
                - name: {{ $key }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ $value.secret_name }}
                      key: {{ $value.secret_key }}
              {{- end }}
          restartPolicy: Never

---
  {{- end }}