{{- range $ms_name, $ms_values := .Values.lightlytics_ms }}
{{/*  hi: map[deployment:map[command:/consumer env:map[MSName:collection-consumer] hpa_enable:no] imageName:collection service:map[targetPort:4242]] */}}
{{- if $ms_values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $ms_name }}
  {{- if $ms_values.service.annotations }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags:
      Name={{ $.Release.Name }}
  {{- range $key, $value := $ms_values.service.annotations }}
  {{- if eq $key "external-dns.alpha.kubernetes.io/hostname" }}
    {{ $key }}: {{ $.Release.Name }}{{ $value }}
  {{- else if or (eq $key "external-dns.alpha.kubernetes.io/ttl") (eq $key "service.beta.kubernetes.io/aws-load-balancer-internal") }}
    {{ $key }}: {{ $value | quote  }}
  {{- else }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
  {{- end }}

spec:
  type: {{ default $.Values.service.default_type $ms_values.service.type }}
  selector:
    app.kubernetes.io/name: {{ $ms_name }}
  ports:
    - protocol: {{ default $.Values.service.default_protocol $ms_values.service.protocol }}
      port: {{ default $.Values.service.default_port $ms_values.service.port }}
      targetPort: {{ default $.Values.service.default_traget_port $ms_values.service.targetPort }}
      name: listener-{{ default $.Values.service.default_port $ms_values.service.port }}
    {{- if $ms_values.service.ssl_enabled }}
    - protocol: {{ default $.Values.service.default_protocol $ms_values.service.protocol }}
      port: 443
      targetPort: {{ default $.Values.service.default_traget_port $ms_values.service.targetPort }}
      name: listener-443
    {{- end }}
---
{{- end }}
{{- end }}