- name: Update neo4j plugins
  hosts: neo4j

  tasks:
  - name: find old gds plugin
    find:
      paths: /var/lib/neo4j/plugins/
      patterns: neo4j-graph-data-science-*
    register: files_to_delete
    become: yes
    become_user: root

  - name: Ansible remove old gds files
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"
    become: yes
    become_user: root

  - name: copy template file
    copy:
      src: ./payloads/neo4j/neo4j.template
      dest: /etc/neo4j/
      owner: neo4j
      group: root
      mode: '0644'
    become: yes
    become_user: root

  - name: Copy gds plugin
    copy:
      src: "{{ gds_jar_file_location }}"
      dest: /var/lib/neo4j/plugins/
      owner: neo4j
      group: adm
      mode: '0664'
    become: yes
    become_user: root

  - name: Restart neo4j service
    systemd:
      state: restarted
      name: neo4j
    become: yes
    throttle: 1
    become_user: root

