---
neo4j:
  hosts:
    10.0.200.187:
    10.0.201.154:
    10.0.201.88:
    10.0.200.84:
    10.0.201.215:
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: ./Lightlytics.pem
    ansible_ssh_common_args: ' -o ProxyCommand="ssh -q ec2-user@52.21.190.71 -i ./Lightlytics.pem -W %h:%p"'

mongodb:
  hosts:
    10.0.200.195:
    10.0.201.229:
    10.0.200.117:
  vars:
    ansible_ssh_user: ec2-user
    ansible_ssh_private_key_file: ~/work/lightlytics-devops/ansible_2ng/Lightlytics.pem
    ansible_ssh_common_args: ' -o ProxyCommand="ssh -q ec2-user@52.21.190.71 -i ~/work/lightlytics-devops/ansible_2ng/Lightlytics.pem -W %h:%p"'

