---
- name: find old gds plugin
  find:
    paths: /var/lib/neo4j/plugins/
    patterns: neo4j-graph-data-science-*
  register: files_to_delete
  become: yes
  become_user: root

- name: Ansible remove old gds files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
  become: yes
  become_user: root

- name: copy template file
  template:
    src: ~/work/lightlytics-devops/ansible-jenkins/roles/neo4j/templates/neo4j.j2
    dest: /etc/neo4j/
    owner: neo4j
    group: root
    mode: '0644'
  become: yes
  become_user: root

- name: Copy gds from s3
  shell: sudo aws s3 cp s3://gds-lightlytics-jars/$(aws s3 ls s3://gds-lightlytics-jars  --recursive | sort | tail -n 1 | awk '{print $4}') /var/lib/neo4j/plugins/
  become: yes
  become_user: root

- name: Restart neo4j service
  systemd:
    state: restarted
    name: neo4j
  become: yes
  throttle: 1
  become_user: root
