name: terraform-plan
on:
  pull_request:
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - run: terraform -chdir=./terraform init
      - run: terraform -chdir=./terraform plan -lock=false -out ./terraform.plan
      - run: terraform -chdir=./terraform show -json ./terraform.plan > ./terraform/plan.json
      - run: ls -la ./terraform/
      - run: cat ./terraform/plan.json
      - uses: jsdaniell/create-json@1.1.2
        with:
          name: metadata.json
          json: '{ "source": { "name":"Github", "event name": "${{ github.event_name }}","repository": "${{ github.repository }}", "base_branch": "${{ github.base_ref }}","branch": "${{ github.head_ref }}","pr_id": ${{ github.event.pull_request.number }}, "commit_hash":"${{ github.sha }}", "user_name": "${{ github.actor }}" } }'
          dir: './terraform/'
      - run: ls -la ./terraform/
      - run: cat ./terraform/metadata.json
#      - run: pip3 install typer
#      - run:  python3 ./terraform/jsonapi.py --path-plan './terraform/plan.json'  --path-metadata './terraform/metadata.json'
#  build:
#    runs-on: ubuntu-latest
#    steps:
      - uses: actions/checkout@v1
        with:
          Path_plan: ./terraform/plan.json
          Path_metadata: ./terraform/metadata.json
